### PR TITLE
Fix sending coin over ranges #216

### LINKED ISSUE #216: Can't send coins over multiple ranges
## Describe the bug

We can't send coins over multiple different ranges.

## To Reproduce

https://github.com/cryptoeconomicslab/plasma-rust-framework/tree/plasma-demo

## Expected behavior

We can send coins with multiple source StateUpdates.

### PR DESCRIPTION
**Pull request by syuhei176**
fixing client logic to support sending coin over multiple previous ranges which can have different block number.

I had to modify ingest_transaction, so I added spec for that before modifying.

It close #216

### CODE REVIEW

File: clients/src/plasma/command.rs [hunk 1]
```diff
@@ -53,16 +53,17 @@ impl FetchBlockRequest {
     }
 }
 
+/// prev_state_block_number is the block numbers which the transaction deprecated
 #[derive(Clone, Debug, AbiDecodable, AbiEncodable)]
 pub struct NewTransactionEvent {
-    pub prev_state_block_number: Integer,
```
Comment (syuhei176) [inline clients/src/plasma/command.rs]: I couldn't add comment before attribute because of `AbiEncodable` or `AbiDecodable` error.

Comment (tkmct) [reply clients/src/plasma/command.rs]: sure!
